language: c

cache:
  directories:
    - NimBinaries

git:
  # when multiple CI builds are queued, the tested commit needs to be in the last X commits cloned with "--depth X"
  depth: 10

os:
  - linux
  - osx

install:
  # build nim from our own branch - this to avoid the day-to-day churn and
  # regressions of the fast-paced Nim development while maintaining the
  # flexibility to apply patches
  - curl -O -L -s -S https://raw.githubusercontent.com/status-im/nimbus-build-system/master/scripts/build_nim.sh
  - env MAKE="make -j2" bash build_nim.sh Nim csources dist/nimble NimBinaries
  - export PATH=$PWD/Nim/bin:$PATH

  - git submodule update --init --recursive

script:
  - cd tests/snappycpp
  - mkdir build
  - cd build && cmake ../ && make
  - cd ../../..
  - cp tests/snappycpp/build/libsnappy.a ./tests/

  - nimble install -y
  - nimble test
